export const DEFAULT_COUNTER_BUTTON_HIGHLIGHT_COLOR = '#80d8f7';
export type DEFAULT_COUNTER_BUTTON_HIGHLIGHT_COLOR = typeof DEFAULT_COUNTER_BUTTON_HIGHLIGHT_COLOR;

export const DEFAULT_COUNTER_BUTTON_HIGHLIGHT_TEXT_COLOR = '#282c34';
export type DEFAULT_COUNTER_BUTTON_HIGHLIGHT_TEXT_COLOR = typeof DEFAULT_COUNTER_BUTTON_HIGHLIGHT_TEXT_COLOR;

export const DEFAULT_COUNTER_VALUE_TEXT_COLOR = '#fff';
export type DEFAULT_COUNTER_VALUE_TEXT_COLOR = typeof DEFAULT_COUNTER_VALUE_TEXT_COLOR;

export const DEFAULT_COUNTER_VALUE_SELECTION_COLOR = '#80d8f7';
export type DEFAULT_COUNTER_VALUE_SELECTION_COLOR = typeof DEFAULT_COUNTER_VALUE_SELECTION_COLOR;
