export const DEFAULT_COUNTER_BUTTON_HIGHLIGHT_COLOR = '#80d8f7';
export type DEFAULT_COUNTER_BUTTON_HIGHLIGHT_COLOR = typeof DEFAULT_COUNTER_BUTTON_HIGHLIGHT_COLOR;

export const DEFAULT_COUNTER_BUTTON_HIGHLIGHT_TEXT_COLOR = '#282c34';
export type DEFAULT_COUNTER_BUTTON_HIGHLIGHT_TEXT_COLOR = typeof DEFAULT_COUNTER_BUTTON_HIGHLIGHT_TEXT_COLOR;

export const DEFAULT_COUNTER_VALUE_FONT_SIZE = '20vmin';
export type DEFAULT_COUNTER_VALUE_FONT_SIZE = typeof DEFAULT_COUNTER_VALUE_FONT_SIZE;

export const DEFAULT_COUNTER_VALUE_TEXT_COLOR = '#fff';
export type DEFAULT_COUNTER_VALUE_TEXT_COLOR = typeof DEFAULT_COUNTER_VALUE_TEXT_COLOR;

export const DEFAULT_COUNTER_VALUE_SELECTION_COLOR = '#80d8f7';
export type DEFAULT_COUNTER_VALUE_SELECTION_COLOR = typeof DEFAULT_COUNTER_VALUE_SELECTION_COLOR;

export const DEFAULT_COUNTER_ICON_HEIGHT = '1em';
export type DEFAULT_COUNTER_ICON_HEIGHT = typeof DEFAULT_COUNTER_ICON_HEIGHT;

export const DEFAULT_COUNTER_ICON_WIDTH = '1em';
export type DEFAULT_COUNTER_ICON_WIDTH = typeof DEFAULT_COUNTER_ICON_WIDTH;
