export const DEFAULT_APP_MAIN_BACKGROUND_COLOR = '#1a2838';
export type DEFAULT_APP_MAIN_BACKGROUND_COLOR = typeof DEFAULT_APP_MAIN_BACKGROUND_COLOR;

export const DEFAULT_APP_MAIN_TEXT_COLOR = '#fff';
export type DEFAULT_APP_MAIN_TEXT_COLOR = typeof DEFAULT_APP_MAIN_TEXT_COLOR;

export const DEFAULT_APP_THEME = 'dark';
export type DEFAULT_APP_THEME = typeof DEFAULT_APP_THEME;
